name: Ubuntu 22.04 CI

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install cysimdjson 
        run: pip install cysimdjson
      - name: Run script
        run: python3 main.py 
      - name: valgrind python3 main.py
        uses: solareenlo/42valgrind-action@v1.0.3
        with:
          flags: "python3 main.py"
