name: Ubuntu 22.04 CI

on: [push, pull_request]

jobs:
  ubuntu-build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install cysimdjson 
        run: pip install cysimdjson
      - name: Run script
        run: python3 main.py
      - name: valgrind
        run: |
          sudo apt-get install -y valgrind
          valgrind -v --leak-check=full --show-leak-kinds=all python3 main.py
